### ISSUE TITLE
Generate 3D mesh for Human36M

### ISSUE THREAD

**Issue by jeroenvb** [nkolot/GraphCMR#9]
Very nice work. The other thread is closed, but I'd like to understand how we may generate the 3D (smpl) meshes for the Human36M dataset.

- Does the H36M dataset contain enough info to generate 3D meshes?

- Is there code available for this process, or did you implement something yourselves?

You mention on your github that you MoSHed the data to get SMPL parameters. On the mosh project page we don't see any code that performs this. 

We are training a modified network from scratch, and need more ground truth 3D meshes. Any info would be much appreciated!

**Comment by geopavlakos** [comment]
For Human3.6M, the SMPL parameters we used for training are the same as the ones used by the HMR approach (https://github.com/akanazawa/hmr). Unfortunately, this data is no longer publicly available due to license limitations. Beyond that, for this work we haven't investigated generating ground truth 3D meshes for Human3.6M.
